routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@front');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/properties', 'HouseController@showProperties')->name('properties');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/thank-you', 'HomeController@thanks')->name('thanks');

Route::resource('admin/quotings','QuotingController');
Route::get('quotings','QuotingController@leadView')->name('lead-view');
Route::post('quotings','QuotingController@createLead')->name('lead-store');
Route::resource('admin/houses','HouseController');
Route::resource('admin/types','TypeController');

resources/views/home.blade.php
@extends('layouts.master')

@section('contents')
<div class="container">
    <h5 class="mb-2 mt-4">Panel informativo</h5>
    <div class="row">
        <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>{{ $sales->count() }}</h3>

                    <p>Ventas realizadas</p>
                </div>
                <div class="icon">
                    <i class="fas fa-shopping-cart"></i>
                </div>
                <a href="{{ route('quotings.index') }}" class="small-box-footer">
                    Gestionar <i class="fas fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>
        <!-- ./col -->

        <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>{{ $quotings->count() }}</h3>

                    <p >Cotizaciones pendientes</p>
                </div>
                <div class="icon">
                    <i class="fas fa-address-book"></i>
                </div>
                <a href="{{ route('quotings.index') }}" class="small-box-footer">
                    Gestionar <i class="fas fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>
        <!-- ./col -->

        <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{ $types->count() }}</h3>

                    <p >Tipos de propiedades</p>
                </div>
                <div class="icon">
                    <i class="fab fa-accusoft"></i>
                </div>
                <a href="{{ route('types.index') }}" class="small-box-footer">
                    Gestionar <i class="fas fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>
        <!-- ./col -->

        <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-primary">
                <div class="inner">
                    <h3>{{ $properties->count() }}</h3>

                    <p >Propiedades</p>
                </div>
                <div class="icon">
                    <i class="fas fa-home"></i>
                </div>
                <a href="{{ route('houses.index') }}" class="small-box-footer">
                    Gestionar <i class="fas fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>
        <!-- ./col -->

    </div>
</div>
@endsection