routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@front');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/properties', 'HouseController@showProperties')->name('properties');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/thank-you', 'HomeController@thanks')->name('thanks');

Route::resource('admin/quotings','QuotingController');
Route::get('quotings','QuotingController@leadView')->name('lead-view');
Route::post('quotings','QuotingController@createLead')->name('lead-store');
Route::resource('admin/houses','HouseController');
Route::resource('admin/types','TypeController');

app/Quoting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Quoting extends Model
{
    //
}

app/Http/Controllers/QuotingController.php
<?php

namespace App\Http\Controllers;

use App\Quoting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class QuotingController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request)
        {
            $query=trim($request->get('searchText'));
            $quotings =  Quoting::where('full_name','LIKE','%'.$query.'%')
                ->where ('status','=','CREADA')
                ->orderBy('id','desc')
                ->paginate(5);
            $query=trim($request->get('searchText'));
            $vieweds =  Quoting::where('full_name','LIKE','%'.$query.'%')
                ->where ('status','=','ATENDIDA')
                ->orWhere ('status','=','RECHAZADA')
                ->orderBy('id','desc')
                ->paginate(5);

            $sales =  Quoting::where('full_name','LIKE','%'.$query.'%')
                ->where ('status','=','VENTA')
                ->orderBy('id','desc')
                ->paginate(5);

            return view('quotings.index', compact('quotings','query','vieweds','sales'));
        }
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $quoting = Quoting::findOrFail($id);
        return view('quotings.show', compact('quoting'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $quoting = Quoting::findOrFail($id);
        return view('quotings.edit', compact('quoting'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request->all());
        $quoting = Quoting::findOrFail($id);
        $quoting->final_price = $request->get('final_price');
        $quoting->status = $request->get('status');
        $quoting->update();

        return redirect()->route('quotings.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function leadView()
    {
        return view('front.quoting');
    }

    public function createLead(Request $request)
    {
        $quoting = new Quoting;
        $quoting->ci = $request->get('ci');
        $quoting->full_name = $request->get('full_name');
        $quoting->phone = $request->get('phone');
        $quoting->email = $request->get('email');
        $quoting->area = $request->get('area');
        $quoting->budget = $request->get('budget');
        $quoting->property_type = $request->get('property_type');
        $quoting->comment = $request->get('comment');
        $quoting->save();

        $data = array(
            'ci' => $quoting->ci,
            'full_name' => $quoting->full_name,
            'area' => $quoting->area,
            'budget' => $quoting->budget,
            'property_type' => $quoting->property_type,
            'comment' => $quoting->comment,
        );

        Mail::send('emails.quoting', $data, function ($message) use( $quoting){
            $message->from($quoting->email, 'Nueva cotizacion');
            $message->to('admin@admin.com')->subject('Asunto');
        });

        return view('front.thank-you', compact('quoting'));
    }
}

resources/views/quotings/partials/delete.blade.php
<!-- Modal -->
<div class="modal fade" id="typeDeleteModal-{{ $type->id }}" tabindex="-1" role="dialog" aria-labelledby="typeDeleteModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="typeCreateModalLabel">Eliminar tipo de inmueble</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('types.destroy', $type->id) }}" method="POST">
                {{ csrf_field() }}
                @method('DELETE')
                <div class="modal-body">
                    <div class="form-group">
                        <p>
                            ¿Desea eliminar el registro?: <strong> {{ $type->name }} </strong>
                        </p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/quotings/partials/details.blade.php
<div class="card-body table-responsive p-0">
    <table class="table table-hover table-bordered">
        <thead>
        <th>ID</th>
        <th>Nombre</th>
        <th>Teléfono</th>
        <th>Email</th>
        <th>Area</th>
        <th>Budget</th>
        <th>Tipo de propiedad</th>
        <th>Oferta cotizada</th>
        <th>Registrada</th>
        <th>Actualizada</th>
        </thead>
        <tbody>
        <tr>
            <td>{{ $quoting->id }}</td>
            <td>{{ $quoting->full_name }}</td>
            <td>{{ $quoting->phone }}</td>
            <td><a href="mailto:{{ $quoting->email }}">{{ $quoting->email }}</a></td>
            <td>{{ $quoting->area }} m2</td>
            <td>$ {{ $quoting->budget }}</td>
            <td>{{ $quoting->property_type }}</td>
            @if( $quoting->final_price)
                <td>$ {{ $quoting->final_price }}</td>
            @else
                <td class="text-info">Sin asignar</td>
            @endif
            <td>{{ $quoting->created_at->diffForHumans() }}</td>
            <td>{{ $quoting->updated_at->diffForHumans() }}</td>
        </tr>
        </tbody>
    </table>
    <hr>
</div>

<p class="p-3 text-muted">
  <strong>Mensaje adicional:</strong>  {{ $quoting->comment }}
</p>

<a href="{{ route('quotings.index') }}" class="btn btn-secondary ml-3 mb-3">Volver</a>

resources/views/quotings/partials/edit-form.blade.php
<div class="card-body table-responsive p-0">
    <table class="table table-hover table-bordered">
        <thead>
        <th>ID</th>
        <th>Nombre</th>
        <th>Teléfono</th>
        <th>Email</th>
        <th>Area</th>
        <th>Budget</th>
        <th>Tipo de propiedad</th>
        <th>Oferta cotizada</th>
        <th>Registrada</th>
        <th>Actualizada</th>
        </thead>
        <tbody>
        <tr>
            <td>{{ $quoting->id }}</td>
            <td>{{ $quoting->full_name }}</td>
            <td>{{ $quoting->phone }}</td>
            <td><a href="mailto:{{ $quoting->email }}">{{ $quoting->email }}</a></td>
            <td>{{ $quoting->area }} m2</td>
            <td>$ {{ $quoting->budget }}</td>
            <td>{{ $quoting->property_type }}</td>
            @if( $quoting->final_price)
                <td>$ {{ $quoting->final_price }}</td>
            @else
                <td class="text-info">Sin asignar</td>
            @endif
            <td>{{ $quoting->created_at->diffForHumans() }}</td>
            <td>{{ $quoting->updated_at->diffForHumans() }}</td>
        </tr>
        </tbody>
    </table>
    <hr>
</div>

<form action="{{ route('quotings.update',$quoting->id) }}" method="POST">
    {{ method_field('PATCH') }}
    {{ csrf_field() }}

    <div class="container">

        <div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="form-group">
                    <label for="name">Precio de oferta</label>
                    <input type="number" placeholder="Precio de cotización" class="form-control" name="final_price" required >
                </div>
            </div>
            <div class="col-sm-12 col-md-6">
                <div class="form-group">
                    <label for="name">Estado de la cotización</label>
                    <select name="status"  class="form-control">
                        <option value="ATENDIDA" selected>Atendida</option>
                        <option value="VENTA">Venta realizada</option>
                        <option value="RECHAZADA">Rechazada por el lead</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <a href="{{ route('quotings.index') }}" class="btn btn-secondary">Cancelar</a>
            <button type="submit" class="btn btn-primary">Actualizar</button>
        </div>
    </div>
</form>

resources/views/quotings/partials/header.blade.php
<!--  Header -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Inicio</a></li>
                    <li class="breadcrumb-item active">Tipo de propiedad</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.header -->

resources/views/quotings/partials/modal-create.blade.php
<!-- Modal -->
<div class="modal fade" id="typeCreateModal" tabindex="-1" role="dialog" aria-labelledby="typeCreateModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="typeCreateModalLabel">Agregar Categoría</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('types.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name">Nombre:</label>
                        <input type="text" placeholder="Nombre de la categoría" class="form-control" name="name" required>
                    </div>

                    <div class="form-group">
                        <label for="status">Estado</label>
                        <select name="status" class="form-control">
                            <option value="1">Activo</option>
                            <option value="0">Inactivo</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/quotings/partials/table.blade.php
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card card-warning">
                <div class="card-header">
                    <h3 class="card-title">Cotizaciones Pendientes</h3>

                    <div class="card-tools">
                        <form action="{{ route('quotings.index') }}" method="GET">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="searchText" class="form-control float-right" placeholder="Buscar registro"
                                       value="{{ $query }}">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-outline-light"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover">
                        <thead>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                        </thead>
                        <tbody>
                        @foreach($quotings as $quoting)
                            <tr>
                                <td>{{ $quoting->id }}</td>
                                <td>{{ $quoting->full_name }}</td>
                                @if($quoting->status === 'CREADA')
                                    <td class="text-danger">
                                        Pendiente de atender
                                    </td>
                                @endif
                                <td>
                                    <a href="{{ route('quotings.show', $quoting->id) }}" class="btn btn-outline-info">Detalles</a>
                                    <a href="{{ route('quotings.edit', $quoting->id) }}" class="btn btn-primary">Editar</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    {{ $quotings->links() }}
                </div>
            </div>
            <!-- /.card  pending-->
        </div>
        <div class="col-md-6">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Cotizaciones Atendidas</h3>

                    <div class="card-tools">
                        <form action="{{ route('quotings.index') }}" method="GET">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="searchText" class="form-control float-right" placeholder="Buscar registro"
                                       value="{{ $query }}">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-outline-light"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover">
                        <thead>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                        </thead>
                        <tbody>
                        @foreach($vieweds as $quoting)
                            <tr>
                                <td>{{ $quoting->id }}</td>
                                <td>{{ $quoting->full_name }}</td>
                                @if($quoting->status === 'ATENDIDA')
                                    <td class="text-success">
                                        Atendida
                                    </td>
                                @endif
                                <td>
                                    <a href="{{ route('quotings.show', $quoting->id) }}" class="btn btn-outline-info">Detalles</a>
                                    <a href="{{ route('quotings.edit', $quoting->id) }}" class="btn btn-primary">Editar</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    {{ $vieweds->links() }}
                </div>
            </div>
            <!-- /.card  pending-->
        </div>
    </div>
    <br>
    <hr>
    <br>
    <div class="row">
        <div class="col-md-12">
            <div class="card card-success">
                <div class="card-header">
                    <h3 class="card-title">Ventas realizadas</h3>

                    <div class="card-tools">
                        <form action="{{ route('quotings.index') }}" method="GET">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="searchText" class="form-control float-right" placeholder="Buscar registro"
                                       value="{{ $query }}">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-outline-light"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover">
                        <thead>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                        </thead>
                        <tbody>
                        @foreach($sales as $quoting)
                            <tr>
                                <td>{{ $quoting->id }}</td>
                                <td>{{ $quoting->full_name }}</td>
                                @if($quoting->status === 'VENTA')
                                    <td class="text-success">
                                        Venta realizada
                                    </td>
                                @endif
                                <td>
                                    <a href="{{ route('quotings.show', $quoting->id) }}" class="btn btn-outline-info">Detalles</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    {{ $vieweds->links() }}
                </div>
            </div>
            <!-- /.card  pending-->
        </div>
    </div>
</div>