routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@front');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/properties', 'HouseController@showProperties')->name('properties');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/thank-you', 'HomeController@thanks')->name('thanks');

Route::resource('admin/quotings','QuotingController');
Route::get('quotings','QuotingController@leadView')->name('lead-view');
Route::post('quotings','QuotingController@createLead')->name('lead-store');
Route::resource('admin/houses','HouseController');
Route::resource('admin/types','TypeController');

resources/views/houses/partials/delete.blade.php
<!-- Modal -->
<div class="modal fade" id="houseDeleteModal-{{ $house->id }}" tabindex="-1" role="dialog" aria-labelledby="houseDeleteModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="houseCreateModalLabel">Eliminar propiedad</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('houses.destroy', $house->id) }}" method="POST">
                {{ csrf_field() }}
                @method('DELETE')
                <div class="modal-body">
                    <div class="form-group">
                        <p>
                            ¿Desea eliminar el registro?: <strong> {{ $house->title }} </strong>
                        </p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/houses/partials/details.blade.php
<div class="container">

    <div class="details" style="display: flex; flex-wrap: wrap; justify-content: space-between;">
        <div class="info">
            <p class="text-muted">
                <strong>Propiedad:</strong> {{ $house->title }}
            </p>
            <p class="text-muted">
                <strong>Ubicación:</strong> {{ $house->location }}
            </p>

            <p class="text-muted">
                <strong>Superficie:</strong> {{ $house->area }} m2
            </p>

            <p class="text-muted">
                <strong>N° de dormitorios:</strong> {{ $house->rooms }}
            </p>

            <p class="text-muted">
                <strong>N° de baños:</strong> {{ $house->bathrooms }}
            </p>

            <p class="text-muted">
                <strong>N° de garages:</strong> {{ $house->garage }}
            </p>

            <p class="text-muted">
                <strong>Precio</strong> {{ $house->price }}
            </p>

            <p class="text-muted">
                <strong>Descripción:</strong> {{ $house->description }}
            </p>
        </div>

        <div class="image">
            <p class="text-muted text-center">
                <strong>Imagen principal</strong>
            </p>
            @if($house->image)
                <img src="{!! url('/uploads/propperties/'.$house->image) !!}" alt="{{ $house->title }}" width="250" height="250" class="img-responsive">
            @else
                <span class="text-danger"> Aún no se ha asignado imagen principal</span>
            @endif
        </div>
    </div>
    <div class="row mb-4">
        <div class="col-sm-12 col-md-5">
            <a href="{{ route('houses.index') }}" class="btn btn-secondary mr-2" >Regresar</a>
        </div>
    </div>

</div>

resources/views/houses/partials/header.blade.php
<!--  Header -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Inicio</a></li>
                    <li class="breadcrumb-item active">Propiedades</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.header -->

resources/views/houses/partials/modal-create.blade.php
<!-- Modal -->
<div class="modal fade" id="houseCreateModal" tabindex="-1" role="dialog" aria-labelledby="houseCreateModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="typeCreateModalLabel">Agregar Propiedad</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('houses.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="title">Título:</label>
                        <input type="text" placeholder="Título de la propiedad" class="form-control" name="title" required>
                    </div>

                    <div class="form-group">
                        <label for="status">Estado</label>
                        <select name="status" class="form-control">
                            <option value="1">Activo</option>
                            <option value="0">Inactivo</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/houses/partials/table.blade.php
<!-- Disparar odal
<button type="button" class="btn btn-outline-dark my-2" data-toggle="modal" data-target="#houseCreateModal">
    Añadir propiedad
</button>
-->

<a href="{{ route('houses.create') }}" class="btn btn-outline-dark my-2">Añadir propiedad</a>

<div class="card card-dark">
    <div class="card-header">
        <h3 class="card-title">Gestión de Propiedades</h3>

        <div class="card-tools">
            <form action="{{ route('houses.index') }}" method="GET">
                <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="searchText" class="form-control float-right" placeholder="Buscar registro"
                           value="{{ $query }}">

                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-light"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-0">
        <table class="table table-hover">
            <thead>
            <th>ID</th>
            <th>Nombre</th>
            <th>Ubicación</th>
            <th>Tipo de propiedad</th>
            <th>Acciones</th>
            </thead>
            <tbody>
            @foreach($houses as $house)
                <tr>
                    <td>{{ $house->id }}</td>
                    <td>{{ $house->title }}</td>
                    <td>{{ $house->location }}</td>
                    <td>{{ $house->type->name }}</td>
                    <td>
                        <a href="{{ route('houses.show', $house->id) }}" class="btn btn-outline-info">Detalles</a>
                        <a href="{{ route('houses.edit', $house->id) }}" class="btn btn-primary">Editar</a>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#houseDeleteModal-{{ $house->id }}">
                            Eliminar
                        </button>
                    </td>
                    @include('houses.partials.delete')
                </tr>
            @endforeach
            </tbody>
        </table>
        @include('houses.partials.modal-create')
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        {{ $houses->links() }}
    </div>
</div>
<!-- /.card -->